// Auto-Generated by FAKE; do not edit
namespace System
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("CoffeeMachine.Tests.Xunit")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "CoffeeMachine.Tests.Xunit"
